

TEST_IMAGE_URL = "https://oaidalleapiprodscus.blob.core.windows.net/private/org-8Lg1eyPSazGmzlYdNRwFIGcn/user-evoJtnwBhHbo7XBsZxrDJ40g/img-QKjWo9mHuXMzOXIa9YDlCdVj.png?st=2024-10-30T20%3A05%3A48Z&se=2024-10-30T22%3A05%3A48Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-10-30T00%3A14%3A42Z&ske=2024-10-31T00%3A14%3A42Z&sks=b&skv=2024-08-04&sig=/VKojffSNWkZIZ3nJNpEVA1k3oYGRAZOaPrQwo8km7I%3D"

TEST_RESPONSE_CONTENT = """In a bustling city where skyscrapers touched the clouds, two iconic figures roamed the night—a place where neon lights illuminated their paths and beats echoed with every step. Playboi Carti and Lil Uzi Vert, two superstars known for their music, their style, and most importantly, their enduring friendship.\n\n%^ An image of Playboi Carti and Lil Uzi Vert walking down a vibrant city street at night, their silhouettes outlined against a backdrop of towering skyscrapers and neon lights. The city is alive with music and energy, reflecting their larger-than-life personas. %^\n\nOne evening, after a sold-out concert, the two found themselves at a deserted playground, a stark contrast to their usual glam. Carti climbed onto a creaky swing, the chains groaning in protest, while Uzi settled into the seat next to him. They rocked gently, the world momentarily fading away.\n\n%^ An image of Playboi Carti and Lil Uzi Vert sitting on swings in an empty playground under a starry sky. The usual noise of the city is replaced by stillness, evoking a sense of calm and nostalgia. %^\n\nWith headphones shared between them, they listened to a track they had created a few years back—a project born not out of business, but pure joy. As the music played, both artists were reminded of their first days, when fame was still a distant dream, and their bond was just beginning to form with shared laughter and endless creativity.\n\n%^ An image of the duo sharing a set of headphones, their expressions nostalgic and thoughtful as they listen to their early track. The backdrop features stars twinkling above, symbolizing their journey and dreams. %^\n\nCarti broke the silence, "Remember when we thought success was all about breaking records?" Uzi nodded, smiling. "Turns out it\'s about the journey and who\'s riding with you." They laughed, a sound that melted the darkness away, sealing the unspoken truths they had understood over the years.\n\n%^ An image of Playboi Carti and Lil Uzi Vert laughing together under the starry night, the empty playground behind them and their friendship symbolically highlighted. The moment captures pure joy and camaraderie. %^\n\nAs the night deepened, they realized that amid the glitz and glamour, the true value lay not in the number of sold records or followers, but in the bond they shared—a friendship that had weathered storms and celebrated triumphs. Together, they walked back to their world, side by side, their path lit by the understanding that friendship was their greatest hit.\n\n%^ An image of Playboi Carti and Lil Uzi Vert walking away from the playground, side by side, illuminated by city lights in the distance. Their bond is palpable, representing the true essence of their journey. %^"""

STORY_GENERATION_PROMPT_TEMPLATE =  """Write a {duration} narrated story about {story_prompt} Format the output as a story narration, with image descriptions inserted at appropriate scene changes.
                Each image description should:
                Be delimited with "%^" before and after the caption.
                Include complete context, and any essential story elements, so each image can be generated independently without prior knowledge of the story.
                For example, structure image captions as:
                “%^ An image of ...%^”
                Use this format throughout the story to clearly describe each scene transition."""

STORY_DATA_FILEPATH = "story_data/"

NARRATION_FILEPATH = "narration_files/"